from typing import Final

BOARD_MAX_PAGE_SIZE: Final = 150
BOARD_MIN_PAGE_SIZE: Final = 1
BOARD_DEFAULT_PAGE_SIZE: Final = 10

POST_MAX_PAGE_SIZE: Final = 100
POST_MIN_PAGE_SIZE: Final = 1
POST_DEFAULT_PAGE_SIZE: Final = 10
