openapi: 3.0.3
info:
  title: Jaram Hub Api 문서
  version: 1.0.0
paths:
  /hubapi/category/:
    $ref: './category_api.yaml#/\hubapi\category\'
  /hubapi/category/{category_id_pk}/:
    $ref: './category_api.yaml#/\hubapi\category\{category_id_pk}\'
