openapi: 3.0.3
info:
  title: Jaram Hub Api 문서
  version: 1.0.0
$ref: './schemas/schemas.yaml'
paths:
  /hubapi/board/:
    $ref: './board_api.yaml#/\hubapi\board\'
  /hubapi/board/{board_id_pk}/:
    $ref: './board_api.yaml#/\hubapi\board\{board_id_pk}\'
x-tagGroups:
  - name: Apis
    tags:
      - board
#  - name: Models
#    tags:
#      - category_model
#      - category_pagination_model
