# Generated by Django 4.0.6 on 2023-12-06 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jgw_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_id_pk',
            field=models.IntegerField(db_column='THUMBNAIL_ID_PK', default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PostIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postindex_content', models.TextField(db_column='POSTINDEX_CONTENT')),
                ('postindex_id', models.ForeignKey(db_column='POSTINDEX_ID', on_delete=django.db.models.deletion.CASCADE, to='jgw_api.post')),
            ],
            options={
                'db_table': 'POSTINDEX',
                'managed': True,
            },
        ),
    ]
