# Generated by Django 4.0.6 on 2022-10-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jgw_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_category_id_pk',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
