# Generated by Django 4.0.6 on 2023-12-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jgw_api', '0002_remove_post_image_image_id_pk_post_thumbnail_id_pk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_id_pk',
            field=models.IntegerField(db_column='THUMBNAIL_ID_PK', default=None, null=True),
        ),
    ]
